### PR TITLE
PS3 integration

### PR DESCRIPTION
**Pull request by branflaker**
This adds support for syncing PS3 titles.
It uses the internal_entitlements endpoint from the PlayStation store and then the store item details page to filter for games, the latter part being inspired by PSDLE (http://repod.github.io/psdle/).
This should resolve this issue: #1

### CODE REVIEW

**Comment by branflaker** [comment]
Just a friendly ping on this.  Is there any interest in this pull request or any changes that need to be made?

**Comment by FriendsOfGalaxy** [comment]
Good work!
Thank we will look into it and let you know if we got any comments.

**Comment by branflaker** [comment]
Thanks for the update!  One note -- this only pulls in digital games.  Physical PS3 games could get pulled in using the trophies endpoint.  If I get a chance, I'll see if I can implement that as well.

**Comment by JakeKydd** [comment]
Nice work @branflaker , would love to see this merged soon!

**Comment by tyrirn** [comment]
@branflaker @FriendsOfGalaxy  Great news, looking forward to see this implemented!

**Comment by FriendsOfGalaxy** [comment]
Apologize for delay in the PR review. We've reached Galaxy team about this and they have ongoing discussion about platforms. They are not ready to handle it yet (for example see platform filter in Galaxy UI), that is why we have to wait.

**Comment by branflaker** [comment]
No problem, thanks for the heads up.

I understand they want to keep all under PSN (which makes sense since they do use the same friends lists, etc.), but I imagine there must be discussions on distinguishing between consoles like PS3, PS4, and Vita.  As it stands right now, the integration will add multiple versions of the same game to your library if you have a copy of the game on multiple systems, but does not indicate which console the game is for.

Anyone who is interested in testing this out, there is a release available to download here:
https://github.com/branflaker/galaxy-integration-psn/releases

**Comment by tyrirn** [comment]
@branflaker I tried installing this but somehow it gets in conflict with the existing PSN integration, the setup gets stuck in 'Starting'stage. I tried to bypass this by disconnecting from the original PSN integration, but, individually, any of then are getting the PS4 games, no PS3 games are listed.

**Comment by tyrirn** [comment]
@branflaker can you please let me know the steps to install this? I really want to try it out.

**Comment by branflaker** [comment]
@tyrirn Find me on the GOG Cafe Discord (username: Branflake) and we can work through it there.
https://discord.gg/372vxnZ

**Comment by FriendsOfGalaxy** [comment]
Hey. I'm sorry for bigger merge conflict. I will try to make this PR happen in the next place

**Comment by sawfear** [comment]
> 
> 
> Thanks for the update! One note -- this only pulls in digital games. Physical PS3 games could get pulled in using the trophies endpoint. If I get a chance, I'll see if I can implement that as well.

Hey nice work! 
Just curious:  Did you get any chance on implementing the pulling of the trophy endpoint? :)
It would be really pleasant for me to view all of my PS3 Games in Galaxy 2.0 aswell as all my trophies

**Comment by branflaker** [comment]
> Hey nice work!
> Just curious: Did you get any chance on implementing the pulling of the trophy endpoint? :)
> It would be really pleasant for me to view all of my PS3 Games in Galaxy 2.0 aswell as all my trophies

Not yet.  I have some new updates that should add platform tagging, but haven't had a chance to fully test it all.  I've been very busy the past few months.  I'll have to make those changes, then fix the merge conflicts with the version here.  Then I can start tinkering with the trophies endpoint.

**Comment by sawfear** [comment]
> 
> 
> > Hey nice work!
> > Just curious: Did you get any chance on implementing the pulling of the trophy endpoint? :)
> > It would be really pleasant for me to view all of my PS3 Games in Galaxy 2.0 aswell as all my trophies
> 
> Thank you!
> Not yet. I have some new updates that should add platform tagging, but haven't had a chance to fully test it all. I've been very busy the past few months. I'll have to make those changes, then fix the merge conflicts with the version here. Then I can start tinkering with the trophies endpoint.

Oh alright, I´m very excited for this feature! :)

**Comment by FriendsOfGalaxy** [comment]
Hello. I'm closing this PR as it branched off too much from the main version. I'm sorry for not taking this right away - that could be possible to merge then.

This plugin turns into "maintenance" mode. See my comment https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/28#issuecomment-963555709
(tldr: PRs can be accepted - hopefully in more haste than this one).

Small PRs are preferable.

**Pull request closed without merging**
